### ISSUE TITLE
Exported track is silent when adding two oscillators

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#123]
@wayfu encountered a problem with exporting one of their synths to executable, which I debugged down to this minimal example:
Adding two oscillators will play back correctly in the tracker, but export to silence when played back from assembled binary.

I attached the yaml file that reproduces the problem, along with the two exported versions (exported from tracker, exported from binary).

[addp_broken.zip](https://github.com/vsariola/sointu/files/13413692/addp_broken.zip)

EDIT: I used Sointu at 82276915235d16b234463138386919259c63f9a7 to reproduce, which is equivalent to the current master.

**Comment by vsariola** [comment]
Stack overflow. The second oscillator uses some temporary variables and there's already 6 elements on the stack (x87 FPU stack has 8 items max). The binary uses the native x86 assembly written synth to render the song; please use -native ending executables to have matching capabilities. It gave stack overflow error right-away when loading your broken file.

The patch can be fixed by reorganizing it as
oscillator-oscillator-addp-envelope-mulp-...

Does this resolve your issue?

**Comment by LeStahL** [comment]
Retested; this is exactly what happens. Thanks!

**Comment by vsariola** [comment]
This is such a foot-gun but I don't know immediate way to avoid this, short of artificially limiting the non-native synth or supplying only -native ending executables.
