### ISSUE TITLE
last clicked button is clicked again when you hit space

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#156]
I accidentally started deleting instruments instead of playing the track in Live just now, after having deleted one instrument on purpose. Sointu still had keyboard focus, and I was hitting space (play), and it just deleted the first instrument, and then the second, ... took me a while to even understand what had happened.

**Comment by vsariola** [comment]
Yeah, known issue: buttons capture focus, even though user probably doesn't want it. It's a feature of gioui buttons that atm cannot be disabled. I can roll my own button widgets but it takes a bit extra lines to implement my own widgets.

Discussed also at #151

**Comment by qm210** [comment]
@wayfu I made a quick fix that is now up to @vsariola to hate (because really shady, but whatchugonnedo),

so if this takes a while and you are similarly annoyed than me, you might at least test https://github.com/LeStahL/sointu/tree/fix/button-spacebar-hack
(has everything the current master has, minus the spacebar stoolification)

**Comment by vsariola** [comment]
This one is now fully merged
