### ISSUE TITLE
Reordering instruments changes track<->instrument assignments

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#163]
Reordering instruments in the tracker (which is required to change sync track order, which in turn can be necessary when having "connected" syncs like `vec4`) proved to be quite painful, because the notes are immediately assigned to different (wrong) instruments and you have to be super careful to get the original track->instrument assignments correctly again (by drag-reordering tracks as well) after such an operation.

Would it be possible to decouple the two reordering operations entirely?

(if this behavior is a size optimization to avoid saving the track order in the assembly export - could we add a "lock tracks and instruments" button that is only available when it makes sense (when all tracks for a specific instrument are adjacent), that allows to simultaneously reorder tracks and instruments?)

**Comment by vsariola** [comment]
The original crazy idea was that track does not associate with instrument. Why? Because one track with 3 voices could be used trigger three different instruments; particularly potentially useful for triggering 3 effect tracks (e.g. first drop, second drop, third drop).

But the practice is that practically no-one uses these advanced features.

Maybe "lock tracks and instruments" button is possible, but I need to think carefully what corner cases mean (for example, what does it mean to move an instrument that is associated with only 50% of a track).

**Comment by LeStahL** [comment]
I think the feature that instruments and tracks are separate things is quite cool and should absolutely stay. The request is rather about the editing behavior (I'd love the tracks to keep their instrument assignment when reordering instruments), so the reordering is less (time and brain consuming) work :)

**Comment by vsariola** [comment]
I am now considering that by default, we could just reorder the tracks when reordering the instruments and do best effort to keep them synchronized, throwing minor warning if the reordering was not possible. Similarly, we could just delete the track(s) when deleting the instruments if there's clear relationship between a track and instrument. Then perhaps holding down CTRL or something like that could be used to avoid this.

**Comment by vsariola** [comment]
Just reporting in: this will result in fundamental refactoring of the model, probably for the good. Manipulating two separate entities as if they would a single entity was quite a bit more "lost nights sleep" than I expected, but it's starting to work... notice in the video that the bd instrument has two tracks associated with it. We can freely reorder the instruments and the tracks follow the reordering, but if we try to pull one of the bd tracks away from another, it complains as this would "split" the bd instrument so that there would be another instrument in the middle.

https://github.com/user-attachments/assets/68e4c7e0-5d6e-4475-957c-62cda23098df

**Comment by LeStahL** [comment]
this is great! solves the problem without loss of generality.

**Comment by vsariola** [comment]
This one was a lot harder than I hoped! But it's merged, let's see what you think of it. Notice the Instrument-Track linking toggle and the new Split Tracks / Split Instruments buttons.

**Comment by LeStahL** [comment]
Thank you for implementing this. Tested it and this makes reordering a lot easier. Super cool <3
