### ISSUE TITLE
Filter Resonance direction...

### ISSUE THREAD

**Issue by wayfu** [vsariola/sointu#177]
Now, I know this is a carryover from 4klang, and people are probably used to it, but... resonance is mapped the wrong way 'round! Would it perhaps at least be possible to reverse it in the GUI?

**Comment by vsariola** [comment]
Well, it's not exactly because of 4klang, but because of the equations used for the filter. Namely, the characteristic polynomial for the filter (z-transform) is `z^2 + (f^4+r*f^2-2)*z - r*f^2 + 1`, where f and r are the two parameters (0..1). So, the reason to show it like that is simply because that's how r appears in the equations. I guess it could be flipped but this would anyway flip it only for display, we are not going flip how it is stored in the .yml (that would break all existing songs), and I think it's a bit gotcha if we flip it for display, yet the modulation of the parameter then suddenly works inverse (as it is not really flipped, it's just flipped when showing it).

**Comment by vsariola** [comment]
I am working on enhancing the scopes and loudness displays of Sointu, but eventually, we'll get the damn Fourier transform of the output. My plan is to show the filter frequency response overlaid with the FFT spectrum, so I think the fact that decreasing r actually increases the height of the resonance peak will be pretty self-explanatory then?

**Comment by wayfu** [comment]
we'll find out! :)

**Comment by vsariola** [comment]
If we just flip it for display, send modulations work weirdly wrong way around, so it's a gotcha.

If we flip it in code (do actual r=1-r in the code), then we waste bytes in the compiled 4k intro.

Thus, I'm inclined to solve this just by "documenting" the behavior of the resonance parameter better, preferably by showing the frequency response. Perhaps we can also show some text next to the resonance parameter, maybe the height of the resonance peak in dB, but I just don't know how to calculate it analytically :)

**Comment by vsariola** [comment]
One more thing: the parameter is actually the damping ratio (https://en.wikipedia.org/wiki/Damping), so case r = 1 is critically damped, with r < 1 having some resonance peak, and r = 0 having infinite resonance peak (no damping). So, one way to fix this would be just call it "damping ratio" but I'm not sure how familiar DSP guys are with this terminology.
