### ISSUE TITLE
tracker: keep window size

### ISSUE THREAD

**Issue by qm210** [vsariola/sointu#180]
is probably a short fix that I can also do one of these days, but just to get it out of my head:

during testing, I get somewhat tired of always having to resize the fresh window. could store the resolution somewhere instead of defaulting to 800x600

**Comment by vsariola** [comment]
There is a subtlety here which is a bit of a bigger refactoring, but not much: currently, modelData is the state of the tracker that is a) rewinded backwards when you undo; b) saved to the recovery file.

I think a) and b) should be different things. Or more specifically, b) should be a larger struct & contain a) as its part. And the window size should be part of b), but not a) (we don't want to undo window resizing).

I think there's a couple of other things too that could be b), like instrEnlarged and commentExpanded etc. Perhaps even the positions of the splits (the bars that you can drag to rescale different parts of the window) should be there, so that we recall as much as possible of how things are laid out when you restart Sointu.

**Comment by vsariola** [comment]
Changing the recovery file structure is a bit nasty, but that's why we are not yet at v1.0 so that we can break these things freely. But if it's possible to make it so that old recovery files are still read correctly, that would be great.

**Comment by vsariola** [comment]
I think this does not play that well with the idea of #184 / #185: if the user has saved a recovery file, do we load the previous window size from the recovery file or the Preferences? So let's stick to the approach taken in #185 i.e. always just honor the preferences. Thus, this can be closed.
