### ISSUE TITLE
Instrument "Save As" is reopened when using enter key to confirm.

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#97]
Using sointu 61776f397afc5f0af7c199f15774bea214c42085 (current master), when saving instruments and pressing the enter key, the "Save As..." dialog will reopen after saving.

**Comment by vsariola** [comment]
Yeah, easy to reproduce and we now know what the problem is: the form closes on a keydown event and gioui buttons consider keyrelease event as triggering a press. Need to check what the proper way to fix it is, whether patching gioui somehow or if there's a way to override the behaviour of buttons just for sointu.

**Comment by vsariola** [comment]
I have submitted a fix to gioui: https://github.com/gioui/gio/pull/120 this should take care of this issue, so this issue will go away when they merge it & I update gioui to the latest version
